Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

PIMA Diabetes Dataset

In [2]:
diabetes_dataset = pd.read_csv('diabetes.csv')

In [3]:
diabetes_dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              8      125             96              0        0   0.0   
1              4      110             92              0        0  37.6   
2             10      168             74              0        0  38.0   
3             10      139             80              0        0  27.1   
4              1      189             60             23      846  30.1   
..           ...      ...            ...            ...      ...   ...   
754           10      101             76             48      180  32.9   
755            2      122             70             27        0  36.8   
756            5      121             72             23      112  26.2   
757            1      126             60              0        0  30.1   
758            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.232   54        1  
1                       0.191   30        0  
2                       0.537   34        1  
3                       1.441   57        0  
4                       0.398   59        1  
..                        ...  ...      ...  
754                     0.171   63        0  
755                     0.340   27        0  
756                     0.245   30        0  
757                     0.349   47        1  
758                     0.315   23        0  

[759 rows x 9 columns]

In [4]:
diabetes_dataset.shape

(759, 9)

In [5]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   759.000000  759.000000     759.000000     759.000000  759.000000   
mean      3.843215  120.815547      69.263505      20.517787   79.569170   
std       3.370746   31.855797      19.263117      15.943895  114.468959   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      63.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   32.000000   
75%       6.000000  140.000000      80.000000      32.000000  127.500000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  759.000000                759.000000  759.000000  759.000000  
mean    32.006851                  0.471087   33.233202    0.346509  
std      7.905760                  0.325669   11.779063    0.476171  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.244500   24.000000    0.000000  
50%     32.000000                  0.375000   29.000000    0.000000  
75%     36.600000                  0.625000   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
diabetes_dataset['Outcome'].value_counts()

0    496
1    263
Name: Outcome, dtype: int64

0 --> Non-Diabetic

1 --> Diabetic

In [7]:
diabetes_dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness    Insulin  \
Outcome                                                                     
0           3.290323  110.050403      68.318548      19.717742  69.157258   
1           4.885932  141.117871      71.045627      22.026616  99.205323   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.315524                  0.431480  31.217742  
1        35.196578                  0.545783  37.034221

In [8]:
# separating the data and labels
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler = MinMaxScaler(feature_range = (0, 1))

In [11]:
scaled_data = scaler.fit_transform(X)

In [12]:
print(scaled_data)

[[0.47058824 0.6281407  0.78688525 ... 0.         0.06575576 0.55      ]
 [0.23529412 0.55276382 0.75409836 ... 0.56035768 0.04824936 0.15      ]
 [0.58823529 0.84422111 0.60655738 ... 0.56631893 0.19598634 0.21666667]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]


In [13]:
X = scaled_data
Y = diabetes_dataset['Outcome']

In [14]:
Y = np.array(Y)

In [15]:
y = []
for i in range(len(Y)):
    y.append([Y[i]])

In [16]:
print(X)
print(Y)

[[0.47058824 0.6281407  0.78688525 ... 0.         0.06575576 0.55      ]
 [0.23529412 0.55276382 0.75409836 ... 0.56035768 0.04824936 0.15      ]
 [0.58823529 0.84422111 0.60655738 ... 0.56631893 0.19598634 0.21666667]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
[1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1
 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0
 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0
 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1
 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1
 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0
 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 

Train Test Split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X,y, test_size = 0.2, stratify=Y, random_state=2)

In [18]:
print(X.shape, X_train.shape, X_test.shape)

(759, 8) (607, 8) (152, 8)


Training the Model

In [19]:
classifier = svm.SVC(kernel='linear')

In [20]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

Model Evaluation

Accuracy Score

In [21]:
# accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [22]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.771004942339374


In [23]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [24]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.7960526315789473


---------------------------------

In [25]:
check_data = pd.read_csv('diabetes_check.csv')

In [26]:
X_check = check_data.drop(columns = 'Outcome', axis=1)
Y_check = check_data['Outcome']

In [27]:
scaler2 = MinMaxScaler(feature_range = (0, 1))
x_check_scaled = scaler2.fit_transform(X_check)

In [28]:
x_check_scaled.shape

(9, 8)

In [29]:
prediction = classifier.predict(x_check_scaled)
prediction

array([0, 0, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [30]:
np.array(Y_check)

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)